### ISSUE TITLE
got  "Ops, something went wront! Smart Contract Downloader"

### ISSUE THREAD

**Issue by chaochao214** [amimaro/smart-contract-downloader#1]
hello
i wanna download code  which address is   0x93c175439726797DcEe24D08e4ac9164E88e7Aee  on   binance smart  chain 
when  i  visit   https://smart-contract-downloader.vercel.app/  
i got  error " Ops, something went wront!"  
![image](https://user-images.githubusercontent.com/30425369/184528743-f2ea62ce-27ce-4edb-ba47-e55c3330d946.png)

**Comment by amimaro** [comment]
Should be working now.

![image](https://user-images.githubusercontent.com/6666978/184532891-63adebc7-ef04-44f8-8db0-f8be6e9f1dfe.png)
