### ISSUE TITLE
is vercel website still work?

### ISSUE THREAD

**Issue by captpickle** [amimaro/smart-contract-downloader#2]
![image](https://user-images.githubusercontent.com/30425369/201507814-d9cb390d-f246-49b8-8704-09bd91b2423c.png)

ethmainnet
address:0xdAC17F958D2ee523a2206206994597C13D831ec7

**Comment by amimaro** [comment]
Hi! I believe it is still working. I could get the contract using the address you sent.
I think that maybe it is a connection issue. Comparing with my screenshot, your github stars counter appears to be empty and mine shows the current count.
Let me know if the issue persist.
I will close this issue for now.

![image](https://user-images.githubusercontent.com/6666978/201541869-781e1779-87dc-412c-80ca-0834a59721cc.png)
