### ISSUE TITLE
UniswapV3 contracts are not downloaded

### ISSUE THREAD

**Issue by AlexBlack772** [amimaro/smart-contract-downloader#4]
Any uniswapv3 contract failed witn an error 'Invalid address' 

https://etherscan.io/address/0x0002e63328169d7feea121f1e32e4f620abf0352
https://etherscan.io/address/0x0001fcbba8eb491c3ccfeddc5a5caba1a98c4c28

**Comment by amimaro** [comment]
Hmm I think that this may be an etherscan API issue. Here is the full output:
```
  {
    "status": "1",
    "message": "OK",
    "result": [
      {
        "SourceCode": "",
        "ABI": "Contract source code not verified",
        "ContractName": "",
        "CompilerVersion": "",
        "OptimizationUsed": "",
        "Runs": "",
        "ConstructorArguments": "",
        "EVMVersion": "Default",
        "Library": "",
        "LicenseType": "Unknown",
        "Proxy": "0",
        "Implementation": "",
        "SwarmSource": ""
      }
    ]
  }
```

But looking at the contract section, 

Note: This contract matches the deployed ByteCode of the Source Code for Contract [0x8f8ef111b67c04eb1641f5ff19ee54cda062f163](https://etherscan.io/address/0x8f8ef111b67c04eb1641f5ff19ee54cda062f163#code) 

I tested here and it load the contract using this address?
Using 0x8f8EF111B67C04Eb1641f5ff19EE54Cda062f163 address works for you?

![image](https://user-images.githubusercontent.com/6666978/210181494-c07ce564-a1ae-4875-8280-52d41b42c173.png)
