### ISSUE TITLE
Adding a cli toolkit for fetching contract from etherscan

### ISSUE THREAD

**Issue by 0xJchen** [amimaro/smart-contract-downloader#7]
It would be convenient to directly fetch the contract from etherscan in terminal.

**Comment by amimaro** [comment]
Thank you for your suggestion.

Here you go: `npx smart-contract-downloader`

Would be great if you could give it a star if you find it helpful.

Best regards!

**Comment by 0xJchen** [comment]
Thank you! That's fantastic :)
